version: '{build}-{branch}'

platform:
    - x64
    - x86

image:
- Visual Studio 2015
- Visual Studio 2017

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      VS_VER: "12 2013"
      SIMD: yes
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      VS_VER: "12 2013"
      SIMD: no
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      VS_VER: "14 2015"
      SIMD: yes
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      VS_VER: "14 2015"
      SIMD: no
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      VS_VER: 15 2017

configuration:
    - Debug
    - Release


before_build:
- cmd: >-
    IF %PLATFORM% == x86 set GENERATOR_PLATFORM=Win32
    IF %PLATFORM% == x64 set GENERATOR_PLATFORM=Win64
- cmd: >-
    mkdir build

    mkdir dist

    cd build

    cmake -G"Visual Studio %VS_VER% %GENERATOR_PLATFORM%" -DCMAKE_INSTALL_PREFIX=.\dist -D WITH_SIMD=%SIMD% -D NASM=yasm ..\

after_build:
    - cmd: cmake --build .\ --target INSTALL

install:
    - cinst yasm

build:
  project: build\mozjpeg.sln
  parallel: true
  verbosity: minimal

test_script:
  - ctest -T Test -j%NUMBER_OF_PROCESSORS%

deploy: off
