version: "{build}-{branch}"

platform:
    - x64
    - x86

image:
- Visual Studio 2015
- Visual Studio 2017

environment:
  matrix:
    - SIMD: yes
    - SIMD: no
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      VS_VER: "12 2013"
          #- "14 2015"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      VS_VER: 15 2017



before_build:
    - cmd: mkdir build
    - cmd: cd build
    - cmd: cmake -G"Visual Studio %VS_VER% Win64" -D WITH_SIMD=%SIMD% -D NASM=yasm ..\

after_build:
    - cmd: cmake --build --target INSTALL

install:
    - cinst yasm

build:
  project: build\mozjpeg.sln
  parallel: true

test_script:
  - ctest -VV

deploy: off
